### ISSUE TITLE
Non blocking svn

### ISSUE THREAD

**Issue by staabm** [joshdifabio/composer#5]
We also still use svn with composer and would love having a non-blocking svn driver.

Did you finalize your work in 
https://github.com/joshdifabio/composer/commit/a06fe229cbd7e02f0a8fd09afd39977d2e8a6ebc or would you consider it still work in progress?

Thank you!

**Comment by joshdifabio** [comment]
Good question! I honestly can't remember but that work is so old I'd be quite surprised if it works with current Composer.

**Comment by staabm** [comment]
No longer required for us, since we will move away from svn
